create table job_position (
	id INT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	job_title VARCHAR(50),
	PRIMARY KEY(id)
);
insert into job_position (id, first_name, last_name, job_title) values (1, 'Patricia', 'Lawson', 'Geological Engineer');
insert into job_position (id, first_name, last_name, job_title) values (2, 'Dorothy', 'Diaz', 'Editor');
insert into job_position (id, first_name, last_name, job_title) values (3, 'Diana', 'James', 'Social Worker');
insert into job_position (id, first_name, last_name, job_title) values (4, 'Janice', 'Harrison', 'Chief Design Engineer');
insert into job_position (id, first_name, last_name, job_title) values (5, 'Terry', 'Olson', 'Speech Pathologist');
insert into job_position (id, first_name, last_name, job_title) values (6, 'Alice', 'Warren', 'Biostatistician IV');
insert into job_position (id, first_name, last_name, job_title) values (7, 'Katherine', 'Lawrence', 'Media Manager I');
insert into job_position (id, first_name, last_name, job_title) values (8, 'Douglas', 'Fowler', 'VP Quality Control');
insert into job_position (id, first_name, last_name, job_title) values (9, 'Kathryn', 'Ramos', 'Desktop Support Technician');
insert into job_position (id, first_name, last_name, job_title) values (10, 'Victor', 'Austin', 'Legal Assistant');
insert into job_position (id, first_name, last_name, job_title) values (11, 'Juan', 'Lee', 'Safety Technician IV');
insert into job_position (id, first_name, last_name, job_title) values (12, 'Terry', 'Wells', 'Civil Engineer');
insert into job_position (id, first_name, last_name, job_title) values (13, 'Virginia', 'Berry', 'Marketing Assistant');
insert into job_position (id, first_name, last_name, job_title) values (14, 'Norma', 'Robinson', 'Civil Engineer');
insert into job_position (id, first_name, last_name, job_title) values (15, 'Ralph', 'Daniels', 'Structural Analysis Engineer');
insert into job_position (id, first_name, last_name, job_title) values (16, 'Thomas', 'Armstrong', 'Civil Engineer');
insert into job_position (id, first_name, last_name, job_title) values (17, 'William', 'Mitchell', 'VP Accounting');
insert into job_position (id, first_name, last_name, job_title) values (18, 'Joshua', 'Simpson', 'Food Chemist');
insert into job_position (id, first_name, last_name, job_title) values (19, 'Helen', 'Nelson', 'VP Marketing');
insert into job_position (id, first_name, last_name, job_title) values (20, 'Dennis', 'Gutierrez', 'Accountant IV');
insert into job_position (id, first_name, last_name, job_title) values (21, 'Eric', 'Howell', 'Technical Writer');
insert into job_position (id, first_name, last_name, job_title) values (22, 'Ruby', 'Green', 'General Manager');
insert into job_position (id, first_name, last_name, job_title) values (23, 'Diane', 'Ruiz', 'Recruiter');
insert into job_position (id, first_name, last_name, job_title) values (24, 'Eugene', 'Henry', 'VP Marketing');
insert into job_position (id, first_name, last_name, job_title) values (25, 'Virginia', 'Day', 'Design Engineer');
insert into job_position (id, first_name, last_name, job_title) values (26, 'Dorothy', 'Little', 'Cost Accountant');
insert into job_position (id, first_name, last_name, job_title) values (27, 'Louise', 'Franklin', 'Environmental Tech');
insert into job_position (id, first_name, last_name, job_title) values (28, 'Justin', 'Edwards', 'Executive Secretary');
insert into job_position (id, first_name, last_name, job_title) values (29, 'Lois', 'White', 'Administrative Officer');
insert into job_position (id, first_name, last_name, job_title) values (30, 'Craig', 'Patterson', 'Occupational Therapist');
insert into job_position (id, first_name, last_name, job_title) values (31, 'Phillip', 'Perez', 'Marketing Assistant');
insert into job_position (id, first_name, last_name, job_title) values (32, 'Roger', 'King', 'Web Designer II');
insert into job_position (id, first_name, last_name, job_title) values (33, 'Nancy', 'Garrett', 'Mechanical Systems Engineer');
insert into job_position (id, first_name, last_name, job_title) values (34, 'Judith', 'Hart', 'Automation Specialist III');
insert into job_position (id, first_name, last_name, job_title) values (35, 'Gary', 'Gardner', 'Actuary');
insert into job_position (id, first_name, last_name, job_title) values (36, 'Donna', 'Woods', 'Executive Secretary');
insert into job_position (id, first_name, last_name, job_title) values (37, 'Harold', 'King', 'Product Engineer');
insert into job_position (id, first_name, last_name, job_title) values (38, 'Judy', 'Gordon', 'VP Marketing');
insert into job_position (id, first_name, last_name, job_title) values (39, 'Nicole', 'Peters', 'General Manager');
insert into job_position (id, first_name, last_name, job_title) values (40, 'Jesse', 'Palmer', 'Librarian');
insert into job_position (id, first_name, last_name, job_title) values (41, 'Lori', 'Jordan', 'Sales Associate');
insert into job_position (id, first_name, last_name, job_title) values (42, 'Kathryn', 'Tucker', 'Software Test Engineer II');
insert into job_position (id, first_name, last_name, job_title) values (43, 'Margaret', 'Lee', 'Registered Nurse');
insert into job_position (id, first_name, last_name, job_title) values (44, 'Ernest', 'Lawson', 'Recruiter');
insert into job_position (id, first_name, last_name, job_title) values (45, 'Barbara', 'Castillo', 'Tax Accountant');
insert into job_position (id, first_name, last_name, job_title) values (46, 'Robert', 'Jenkins', 'Product Engineer');
insert into job_position (id, first_name, last_name, job_title) values (47, 'Jeremy', 'Johnston', 'Administrative Officer');
insert into job_position (id, first_name, last_name, job_title) values (48, 'Annie', 'Hansen', 'Librarian');
insert into job_position (id, first_name, last_name, job_title) values (49, 'Jessica', 'Oliver', 'Research Associate');
insert into job_position (id, first_name, last_name, job_title) values (50, 'Victor', 'Morales', 'Paralegal');
insert into job_position (id, first_name, last_name, job_title) values (51, 'John', 'Harper', 'Software Test Engineer III');
insert into job_position (id, first_name, last_name, job_title) values (52, 'Elizabeth', 'Martin', 'Payment Adjustment Coordinator');
insert into job_position (id, first_name, last_name, job_title) values (53, 'Gregory', 'Snyder', 'Chief Design Engineer');
insert into job_position (id, first_name, last_name, job_title) values (54, 'Roger', 'Mendoza', 'Structural Engineer');
insert into job_position (id, first_name, last_name, job_title) values (55, 'Mark', 'Riley', 'Environmental Tech');
insert into job_position (id, first_name, last_name, job_title) values (56, 'Gloria', 'Welch', 'Chief Design Engineer');
insert into job_position (id, first_name, last_name, job_title) values (57, 'Alan', 'Payne', 'Assistant Professor');
insert into job_position (id, first_name, last_name, job_title) values (58, 'Diana', 'Stewart', 'Paralegal');
insert into job_position (id, first_name, last_name, job_title) values (59, 'Kevin', 'Anderson', 'Graphic Designer');
insert into job_position (id, first_name, last_name, job_title) values (60, 'Shirley', 'Dixon', 'Mechanical Systems Engineer');
insert into job_position (id, first_name, last_name, job_title) values (61, 'Louis', 'Allen', 'VP Marketing');
insert into job_position (id, first_name, last_name, job_title) values (62, 'Wanda', 'Brooks', 'Design Engineer');
insert into job_position (id, first_name, last_name, job_title) values (63, 'Jimmy', 'Reid', 'Associate Professor');
insert into job_position (id, first_name, last_name, job_title) values (64, 'Harry', 'Little', 'Project Manager');
insert into job_position (id, first_name, last_name, job_title) values (65, 'Arthur', 'Larson', 'Information Systems Manager');
insert into job_position (id, first_name, last_name, job_title) values (66, 'Margaret', 'Reed', 'Information Systems Manager');
insert into job_position (id, first_name, last_name, job_title) values (67, 'John', 'Morgan', 'Environmental Specialist');
insert into job_position (id, first_name, last_name, job_title) values (68, 'Janet', 'Henry', 'Associate Professor');
insert into job_position (id, first_name, last_name, job_title) values (69, 'Daniel', 'Turner', 'Safety Technician I');
insert into job_position (id, first_name, last_name, job_title) values (70, 'Clarence', 'Hunter', 'Database Administrator IV');
insert into job_position (id, first_name, last_name, job_title) values (71, 'Heather', 'Knight', 'Operator');
insert into job_position (id, first_name, last_name, job_title) values (72, 'Ralph', 'Hunter', 'Research Nurse');
insert into job_position (id, first_name, last_name, job_title) values (73, 'Billy', 'Matthews', 'Web Developer IV');
insert into job_position (id, first_name, last_name, job_title) values (74, 'James', 'Freeman', 'Sales Associate');
insert into job_position (id, first_name, last_name, job_title) values (75, 'Cynthia', 'Spencer', 'Account Representative IV');
insert into job_position (id, first_name, last_name, job_title) values (76, 'Martha', 'Rivera', 'Assistant Professor');
insert into job_position (id, first_name, last_name, job_title) values (77, 'Kenneth', 'Mendoza', 'Automation Specialist I');
insert into job_position (id, first_name, last_name, job_title) values (78, 'Todd', 'Hernandez', 'Technical Writer');
insert into job_position (id, first_name, last_name, job_title) values (79, 'Keith', 'Hudson', 'VP Accounting');
insert into job_position (id, first_name, last_name, job_title) values (80, 'Peter', 'Scott', 'Analog Circuit Design manager');
insert into job_position (id, first_name, last_name, job_title) values (81, 'Jennifer', 'Gilbert', 'Quality Control Specialist');
insert into job_position (id, first_name, last_name, job_title) values (82, 'Carl', 'Jenkins', 'Human Resources Assistant III');
insert into job_position (id, first_name, last_name, job_title) values (83, 'Alan', 'Cunningham', 'Analog Circuit Design manager');
insert into job_position (id, first_name, last_name, job_title) values (84, 'Gerald', 'Torres', 'Dental Hygienist');
insert into job_position (id, first_name, last_name, job_title) values (85, 'Jane', 'Woods', 'Electrical Engineer');
insert into job_position (id, first_name, last_name, job_title) values (86, 'William', 'Dunn', 'Speech Pathologist');
insert into job_position (id, first_name, last_name, job_title) values (87, 'Deborah', 'Bell', 'Compensation Analyst');
insert into job_position (id, first_name, last_name, job_title) values (88, 'Louise', 'Roberts', 'Director of Sales');
insert into job_position (id, first_name, last_name, job_title) values (89, 'Theresa', 'Bryant', 'Dental Hygienist');
insert into job_position (id, first_name, last_name, job_title) values (90, 'Tammy', 'Murphy', 'Data Coordiator');
insert into job_position (id, first_name, last_name, job_title) values (91, 'Victor', 'Cook', 'Physical Therapy Assistant');
insert into job_position (id, first_name, last_name, job_title) values (92, 'Peter', 'Little', 'GIS Technical Architect');
insert into job_position (id, first_name, last_name, job_title) values (93, 'Jimmy', 'Bennett', 'Junior Executive');
insert into job_position (id, first_name, last_name, job_title) values (94, 'Kathleen', 'Richardson', 'Safety Technician IV');
insert into job_position (id, first_name, last_name, job_title) values (95, 'Gregory', 'Adams', 'General Manager');
insert into job_position (id, first_name, last_name, job_title) values (96, 'Mildred', 'Vasquez', 'Business Systems Development Analyst');
insert into job_position (id, first_name, last_name, job_title) values (97, 'James', 'Perkins', 'Recruiter');
insert into job_position (id, first_name, last_name, job_title) values (98, 'Adam', 'Ward', 'Geologist III');
insert into job_position (id, first_name, last_name, job_title) values (99, 'Debra', 'Butler', 'Junior Executive');
insert into job_position (id, first_name, last_name, job_title) values (100, 'Louis', 'Fernandez', 'GIS Technical Architect');
insert into job_position (id, first_name, last_name, job_title) values (101, 'Willie', 'Lawson', 'Senior Cost Accountant');
insert into job_position (id, first_name, last_name, job_title) values (102, 'Catherine', 'Black', 'Sales Associate');
insert into job_position (id, first_name, last_name, job_title) values (103, 'Aaron', 'Murray', 'Research Nurse');
insert into job_position (id, first_name, last_name, job_title) values (104, 'Jeffrey', 'Jones', 'Human Resources Manager');
insert into job_position (id, first_name, last_name, job_title) values (105, 'Anna', 'James', 'Executive Secretary');
insert into job_position (id, first_name, last_name, job_title) values (106, 'Justin', 'Garrett', 'Marketing Manager');
insert into job_position (id, first_name, last_name, job_title) values (107, 'Rose', 'Bryant', 'Account Executive');
insert into job_position (id, first_name, last_name, job_title) values (108, 'Charles', 'Meyer', 'Help Desk Technician');
insert into job_position (id, first_name, last_name, job_title) values (109, 'Henry', 'Andrews', 'Nurse Practicioner');
insert into job_position (id, first_name, last_name, job_title) values (110, 'Doris', 'Harris', 'Administrative Officer');
insert into job_position (id, first_name, last_name, job_title) values (111, 'Katherine', 'Hunt', 'Research Assistant IV');
insert into job_position (id, first_name, last_name, job_title) values (112, 'Bruce', 'Medina', 'Junior Executive');
insert into job_position (id, first_name, last_name, job_title) values (113, 'Jack', 'Ward', 'Recruiting Manager');
insert into job_position (id, first_name, last_name, job_title) values (114, 'Robin', 'Carter', 'Data Coordiator');
insert into job_position (id, first_name, last_name, job_title) values (115, 'Lori', 'Fox', 'Help Desk Operator');
insert into job_position (id, first_name, last_name, job_title) values (116, 'Doris', 'Ramos', 'Environmental Specialist');
insert into job_position (id, first_name, last_name, job_title) values (117, 'Roy', 'Richards', 'Dental Hygienist');
insert into job_position (id, first_name, last_name, job_title) values (118, 'Lisa', 'James', 'Design Engineer');
insert into job_position (id, first_name, last_name, job_title) values (119, 'Kelly', 'Little', 'Automation Specialist II');
insert into job_position (id, first_name, last_name, job_title) values (120, 'Roy', 'Alexander', 'Executive Secretary');
insert into job_position (id, first_name, last_name, job_title) values (121, 'Julie', 'Butler', 'Legal Assistant');
insert into job_position (id, first_name, last_name, job_title) values (122, 'Bobby', 'Russell', 'Desktop Support Technician');
insert into job_position (id, first_name, last_name, job_title) values (123, 'Susan', 'Ferguson', 'Senior Cost Accountant');
insert into job_position (id, first_name, last_name, job_title) values (124, 'Ryan', 'Stone', 'Safety Technician II');
insert into job_position (id, first_name, last_name, job_title) values (125, 'Timothy', 'Coleman', 'Accountant III');
insert into job_position (id, first_name, last_name, job_title) values (126, 'Harold', 'Butler', 'Tax Accountant');
insert into job_position (id, first_name, last_name, job_title) values (127, 'George', 'Hall', 'Office Assistant II');
insert into job_position (id, first_name, last_name, job_title) values (128, 'Joshua', 'Rice', 'Geologist II');
insert into job_position (id, first_name, last_name, job_title) values (129, 'Rachel', 'James', 'Chief Design Engineer');
insert into job_position (id, first_name, last_name, job_title) values (130, 'Andrea', 'Ramirez', 'Associate Professor');
insert into job_position (id, first_name, last_name, job_title) values (131, 'George', 'Harper', 'Chief Design Engineer');
insert into job_position (id, first_name, last_name, job_title) values (132, 'Gerald', 'Miller', 'Programmer IV');
insert into job_position (id, first_name, last_name, job_title) values (133, 'Carlos', 'Flores', 'Physical Therapy Assistant');
insert into job_position (id, first_name, last_name, job_title) values (134, 'Sharon', 'Nichols', 'Desktop Support Technician');
insert into job_position (id, first_name, last_name, job_title) values (135, 'Frank', 'Shaw', 'Media Manager III');
insert into job_position (id, first_name, last_name, job_title) values (136, 'Patrick', 'Hanson', 'Chief Design Engineer');
insert into job_position (id, first_name, last_name, job_title) values (137, 'Shawn', 'Freeman', 'Software Engineer II');
insert into job_position (id, first_name, last_name, job_title) values (138, 'Kelly', 'Owens', 'GIS Technical Architect');
insert into job_position (id, first_name, last_name, job_title) values (139, 'Sharon', 'Carter', 'Account Coordinator');
insert into job_position (id, first_name, last_name, job_title) values (140, 'Bobby', 'Johnston', 'Senior Quality Engineer');
insert into job_position (id, first_name, last_name, job_title) values (141, 'Ann', 'Hayes', 'Research Nurse');
insert into job_position (id, first_name, last_name, job_title) values (142, 'Anna', 'Clark', 'Computer Systems Analyst III');
insert into job_position (id, first_name, last_name, job_title) values (143, 'Maria', 'Frazier', 'Research Associate');
insert into job_position (id, first_name, last_name, job_title) values (144, 'Patricia', 'Martin', 'Programmer IV');
insert into job_position (id, first_name, last_name, job_title) values (145, 'Charles', 'Lawson', 'Geologist II');
insert into job_position (id, first_name, last_name, job_title) values (146, 'Betty', 'Taylor', 'Accounting Assistant I');
insert into job_position (id, first_name, last_name, job_title) values (147, 'Justin', 'Reid', 'Desktop Support Technician');
insert into job_position (id, first_name, last_name, job_title) values (148, 'Jessica', 'Rice', 'Administrative Officer');
insert into job_position (id, first_name, last_name, job_title) values (149, 'Brenda', 'Stephens', 'Budget/Accounting Analyst IV');
insert into job_position (id, first_name, last_name, job_title) values (150, 'Janice', 'Allen', 'Environmental Specialist');
insert into job_position (id, first_name, last_name, job_title) values (151, 'Ruth', 'Carter', 'Accountant II');
insert into job_position (id, first_name, last_name, job_title) values (152, 'Wanda', 'Walker', 'Research Nurse');
insert into job_position (id, first_name, last_name, job_title) values (153, 'Keith', 'Webb', 'Graphic Designer');
insert into job_position (id, first_name, last_name, job_title) values (154, 'Matthew', 'Ruiz', 'Statistician IV');
insert into job_position (id, first_name, last_name, job_title) values (155, 'Roy', 'Howard', 'Quality Engineer');
insert into job_position (id, first_name, last_name, job_title) values (156, 'Jacqueline', 'Jacobs', 'Mechanical Systems Engineer');
insert into job_position (id, first_name, last_name, job_title) values (157, 'Nicholas', 'Mills', 'Physical Therapy Assistant');
insert into job_position (id, first_name, last_name, job_title) values (158, 'Gloria', 'Davis', 'Assistant Media Planner');
insert into job_position (id, first_name, last_name, job_title) values (159, 'Christopher', 'Montgomery', 'Dental Hygienist');
insert into job_position (id, first_name, last_name, job_title) values (160, 'Betty', 'Graham', 'Nuclear Power Engineer');
insert into job_position (id, first_name, last_name, job_title) values (161, 'Tammy', 'Richards', 'Desktop Support Technician');
insert into job_position (id, first_name, last_name, job_title) values (162, 'Sharon', 'Nelson', 'Biostatistician III');
insert into job_position (id, first_name, last_name, job_title) values (163, 'Jennifer', 'Knight', 'Environmental Tech');
insert into job_position (id, first_name, last_name, job_title) values (164, 'Carolyn', 'Cook', 'Structural Engineer');
insert into job_position (id, first_name, last_name, job_title) values (165, 'Benjamin', 'Phillips', 'Tax Accountant');
insert into job_position (id, first_name, last_name, job_title) values (166, 'Steve', 'Harper', 'Systems Administrator IV');
insert into job_position (id, first_name, last_name, job_title) values (167, 'Sara', 'Castillo', 'Editor');
insert into job_position (id, first_name, last_name, job_title) values (168, 'Donna', 'Montgomery', 'Senior Cost Accountant');
insert into job_position (id, first_name, last_name, job_title) values (169, 'Beverly', 'Gordon', 'Occupational Therapist');
insert into job_position (id, first_name, last_name, job_title) values (170, 'Kevin', 'Reid', 'Human Resources Manager');
insert into job_position (id, first_name, last_name, job_title) values (171, 'Kevin', 'Castillo', 'Research Nurse');
insert into job_position (id, first_name, last_name, job_title) values (172, 'Edward', 'Reyes', 'VP Quality Control');
insert into job_position (id, first_name, last_name, job_title) values (173, 'Juan', 'Berry', 'Structural Analysis Engineer');
insert into job_position (id, first_name, last_name, job_title) values (174, 'Scott', 'Daniels', 'Programmer Analyst III');
insert into job_position (id, first_name, last_name, job_title) values (175, 'Jerry', 'Cooper', 'Assistant Professor');
insert into job_position (id, first_name, last_name, job_title) values (176, 'Edward', 'Medina', 'VP Quality Control');
insert into job_position (id, first_name, last_name, job_title) values (177, 'Kenneth', 'Green', 'Administrative Assistant III');
insert into job_position (id, first_name, last_name, job_title) values (178, 'Roy', 'Wilson', 'Information Systems Manager');
insert into job_position (id, first_name, last_name, job_title) values (179, 'Jose', 'Harris', 'Assistant Media Planner');
insert into job_position (id, first_name, last_name, job_title) values (180, 'Phyllis', 'Rogers', 'Administrative Assistant IV');
insert into job_position (id, first_name, last_name, job_title) values (181, 'Diana', 'Hayes', 'Civil Engineer');
insert into job_position (id, first_name, last_name, job_title) values (182, 'Michelle', 'Ford', 'Internal Auditor');
insert into job_position (id, first_name, last_name, job_title) values (183, 'Ruby', 'Harris', 'Senior Editor');
insert into job_position (id, first_name, last_name, job_title) values (184, 'Edward', 'Duncan', 'Speech Pathologist');
insert into job_position (id, first_name, last_name, job_title) values (185, 'Carlos', 'Rivera', 'Mechanical Systems Engineer');
insert into job_position (id, first_name, last_name, job_title) values (186, 'Kevin', 'Williamson', 'Web Designer II');
insert into job_position (id, first_name, last_name, job_title) values (187, 'Sarah', 'Bradley', 'Actuary');
insert into job_position (id, first_name, last_name, job_title) values (188, 'Lawrence', 'Tucker', 'Recruiter');
insert into job_position (id, first_name, last_name, job_title) values (189, 'James', 'Spencer', 'Office Assistant I');
insert into job_position (id, first_name, last_name, job_title) values (190, 'Ruby', 'Murray', 'Cost Accountant');
insert into job_position (id, first_name, last_name, job_title) values (191, 'Billy', 'Willis', 'Technical Writer');
insert into job_position (id, first_name, last_name, job_title) values (192, 'Brenda', 'Washington', 'Electrical Engineer');
insert into job_position (id, first_name, last_name, job_title) values (193, 'Donna', 'Chapman', 'Help Desk Technician');
insert into job_position (id, first_name, last_name, job_title) values (194, 'Sean', 'Oliver', 'Marketing Assistant');
insert into job_position (id, first_name, last_name, job_title) values (195, 'Margaret', 'Taylor', 'Automation Specialist III');
insert into job_position (id, first_name, last_name, job_title) values (196, 'Lisa', 'Payne', 'Graphic Designer');
insert into job_position (id, first_name, last_name, job_title) values (197, 'Daniel', 'Campbell', 'Sales Representative');
insert into job_position (id, first_name, last_name, job_title) values (198, 'Evelyn', 'Harvey', 'Community Outreach Specialist');
insert into job_position (id, first_name, last_name, job_title) values (199, 'Martha', 'Schmidt', 'Design Engineer');
insert into job_position (id, first_name, last_name, job_title) values (200, 'Bruce', 'Alexander', 'Help Desk Technician');
insert into job_position (id, first_name, last_name, job_title) values (201, 'Catherine', 'Garza', 'Budget/Accounting Analyst I');
insert into job_position (id, first_name, last_name, job_title) values (202, 'Peter', 'Gonzalez', 'Database Administrator II');
insert into job_position (id, first_name, last_name, job_title) values (203, 'Brenda', 'Bell', 'Geological Engineer');
insert into job_position (id, first_name, last_name, job_title) values (204, 'Teresa', 'Price', 'Marketing Manager');
insert into job_position (id, first_name, last_name, job_title) values (205, 'Johnny', 'Warren', 'Information Systems Manager');
insert into job_position (id, first_name, last_name, job_title) values (206, 'Lillian', 'Hernandez', 'Analyst Programmer');
insert into job_position (id, first_name, last_name, job_title) values (207, 'Jeffrey', 'Walker', 'Database Administrator II');
insert into job_position (id, first_name, last_name, job_title) values (208, 'Daniel', 'Turner', 'Operator');
insert into job_position (id, first_name, last_name, job_title) values (209, 'Julie', 'Griffin', 'VP Marketing');
insert into job_position (id, first_name, last_name, job_title) values (210, 'Betty', 'Burns', 'Desktop Support Technician');
insert into job_position (id, first_name, last_name, job_title) values (211, 'Jacqueline', 'Adams', 'Chief Design Engineer');
insert into job_position (id, first_name, last_name, job_title) values (212, 'Peter', 'Wilson', 'Information Systems Manager');
insert into job_position (id, first_name, last_name, job_title) values (213, 'Richard', 'Miller', 'Assistant Manager');
insert into job_position (id, first_name, last_name, job_title) values (214, 'Philip', 'Payne', 'Structural Engineer');
insert into job_position (id, first_name, last_name, job_title) values (215, 'Andrea', 'Robinson', 'Research Assistant III');
insert into job_position (id, first_name, last_name, job_title) values (216, 'Laura', 'Schmidt', 'Registered Nurse');
insert into job_position (id, first_name, last_name, job_title) values (217, 'Larry', 'Burton', 'Pharmacist');
insert into job_position (id, first_name, last_name, job_title) values (218, 'Jessica', 'Lynch', 'Paralegal');
insert into job_position (id, first_name, last_name, job_title) values (219, 'Christine', 'Shaw', 'Structural Analysis Engineer');
insert into job_position (id, first_name, last_name, job_title) values (220, 'Bruce', 'Hunt', 'Desktop Support Technician');
insert into job_position (id, first_name, last_name, job_title) values (221, 'George', 'Daniels', 'Safety Technician IV');
insert into job_position (id, first_name, last_name, job_title) values (222, 'Jonathan', 'Andrews', 'Senior Developer');
insert into job_position (id, first_name, last_name, job_title) values (223, 'Kelly', 'Larson', 'Accounting Assistant III');
insert into job_position (id, first_name, last_name, job_title) values (224, 'Cheryl', 'Peterson', 'Biostatistician I');
insert into job_position (id, first_name, last_name, job_title) values (225, 'Emily', 'Alexander', 'Chemical Engineer');
insert into job_position (id, first_name, last_name, job_title) values (226, 'Todd', 'Morrison', 'Graphic Designer');
insert into job_position (id, first_name, last_name, job_title) values (227, 'David', 'Ramirez', 'Research Associate');
insert into job_position (id, first_name, last_name, job_title) values (228, 'Angela', 'Oliver', 'VP Quality Control');
insert into job_position (id, first_name, last_name, job_title) values (229, 'Eugene', 'Graham', 'Safety Technician III');
insert into job_position (id, first_name, last_name, job_title) values (230, 'Kathryn', 'Greene', 'Project Manager');
insert into job_position (id, first_name, last_name, job_title) values (231, 'Steven', 'George', 'Teacher');
insert into job_position (id, first_name, last_name, job_title) values (232, 'Earl', 'Ray', 'Project Manager');
insert into job_position (id, first_name, last_name, job_title) values (233, 'Albert', 'Smith', 'Electrical Engineer');
insert into job_position (id, first_name, last_name, job_title) values (234, 'Tammy', 'Perkins', 'Occupational Therapist');
insert into job_position (id, first_name, last_name, job_title) values (235, 'Heather', 'Dunn', 'Senior Editor');
insert into job_position (id, first_name, last_name, job_title) values (236, 'Larry', 'Burton', 'Social Worker');
insert into job_position (id, first_name, last_name, job_title) values (237, 'Gloria', 'Sullivan', 'Product Engineer');
insert into job_position (id, first_name, last_name, job_title) values (238, 'Johnny', 'Murray', 'Civil Engineer');
insert into job_position (id, first_name, last_name, job_title) values (239, 'Laura', 'Little', 'Systems Administrator I');
insert into job_position (id, first_name, last_name, job_title) values (240, 'Jesse', 'Kelley', 'Biostatistician III');
insert into job_position (id, first_name, last_name, job_title) values (241, 'Sharon', 'Hicks', 'Recruiting Manager');
insert into job_position (id, first_name, last_name, job_title) values (242, 'Cheryl', 'Lane', 'Registered Nurse');
insert into job_position (id, first_name, last_name, job_title) values (243, 'David', 'Hawkins', 'Analog Circuit Design manager');
insert into job_position (id, first_name, last_name, job_title) values (244, 'Nicole', 'Garza', 'Business Systems Development Analyst');
insert into job_position (id, first_name, last_name, job_title) values (245, 'Doris', 'Rodriguez', 'Help Desk Technician');
insert into job_position (id, first_name, last_name, job_title) values (246, 'Jacqueline', 'Barnes', 'Human Resources Assistant IV');
insert into job_position (id, first_name, last_name, job_title) values (247, 'Kelly', 'Simmons', 'Professor');
insert into job_position (id, first_name, last_name, job_title) values (248, 'Ashley', 'Morgan', 'Occupational Therapist');
insert into job_position (id, first_name, last_name, job_title) values (249, 'Johnny', 'Patterson', 'Quality Engineer');
insert into job_position (id, first_name, last_name, job_title) values (250, 'Kathleen', 'Hunt', 'Sales Representative');
